// List of supported symbols
export const SYMBOLS: Record<string, { symbol: string; description: string }> = {
    CI_pipeline_running: { symbol: "🏗🔄", description: "🏗🔄 CI pipeline in progress; Automated build" },
    alert: { symbol: "❗", description: "❗ Alert; Important notice; Warning; Attention" },
    alert_siren: { symbol: "🚨", description: "🚨 Emergency alert; Critical issue; Alarm" },
    ancor: { symbol: "⚓", description: "⚓ Anchor; Bookmark; Reference point; Stability" },
    api: { symbol: "🌐", description: "🌐 API; Web service; Endpoint; Interface" },
    api_error: { symbol: "🌐🔥", description: "🌐🔥 API failure; Endpoint issue" },
    api_success: { symbol: "🌐✅", description: "🌐✅ API working; Response OK" },
    archive: { symbol: "🗄", description: "🗄 Archive; Data storage; Retention; Backup" },
    async: { symbol: "⏳", description: "⏳ Asynchronous; Latency; Delayed response; Waiting; Time;" },
    automation: { symbol: "⚙️", description: "⚙️ Automation; DevOps; Workflow; Process" },
    automation_triggered: { symbol: "⚙️🔁", description: "⚙️🔁 Automated job triggered; CI/CD execution" },
    bank: { symbol: "🏦", description: "🏦 Bank; Financial transactions; Currency; Money" },
    battery: { symbol: "🔋", description: "🔋 Battery; Power; Energy; Charge" },
    bell: { symbol: "🔔", description: "🔔 Notification; Alert; Reminder; Ring" },
    bolt: { symbol: "⚡", description: "⚡ Fast response; High performance; Speed" },
    bug: { symbol: "🐞", description: "🐞 Bug; Debugging; Error fixing; Issue" },
    build_failure: { symbol: "🏗❌", description: "🏗❌ Build failed; CI/CD error" },
    build_pipeline: { symbol: "🏗", description: "🏗 CI/CD pipeline; Automated builds; Continuous integration" },
    build_success: { symbol: "🏗✅", description: "🏗✅ Build successful; CI/CD passed" },
    bullseye: { symbol: "🎯", description: "🎯 Goal; Target; Milestone; Objective" },
    calendar: { symbol: "📅", description: "📅 Scheduling; Due date; Calendar; Events" },
    chart: { symbol: "📊", description: "📊 Chart; Data visualization; Graph; Statistics" },
    checkmark: { symbol: "✅", description: "✅ Complete; Success; Passed; Confirmed" },
    clipboard: { symbol: "📋", description: "📋 List; Copy & Paste; Tasks; Notes" },
    clock: { symbol: "🕒", description: "🕒 Time; Schedule; Deadline; Timing" },
    cloud: { symbol: "☁️", description: "☁️ Cloud computing; AWS; Azure; GCP; Internet" },
    cloud_deploy: { symbol: "☁️🚀", description: "☁️🚀 Cloud deployment; Serverless deployment" },
    cloud_function: { symbol: "☁️λ", description: "☁️λ Serverless function; Cloud Lambda" },
    cloud_security: { symbol: "☁️🔒", description: "☁️🔒 Cloud security; Authentication required" },
    cloud_sync: { symbol: "☁️🔄", description: "☁️🔄 Cloud sync; Data replication; Synchronization" },
    commit: { symbol: "📌", description: "📌 Git Commit; Version checkpoint; Save" },
    commit_conflict: { symbol: "📌⚔️", description: "📌⚔️ Merge conflict; Git issue" },
    commit_success: { symbol: "📌✅", description: "📌✅ Commit successful; Version saved" },
    computer: { symbol: "💻", description: "💻 Computer; Workstation; Development; PC" },
    confetti: { symbol: "🎉", description: "🎉 Celebration; Success; Achievement; Party" },
    construction: { symbol: "🚧", description: "🚧 Work in progress; Under construction; Development" },
    container_failure: { symbol: "📦❌", description: "📦❌ Docker container failure; Check logs" },
    container_running: { symbol: "📦✅", description: "📦✅ Docker container running; No issues" },
    cpu: { symbol: "💻", description: "💻 CPU; Processing; Computation; Performance" },
    crash: { symbol: "💥", description: "💥 System crash; Fatal error; Failure" },
    cross_mark: { symbol: "❌", description: "❌ Delete; Remove; Error; Cancel" },
    database: { symbol: "🗂", description: "🗂 Database; SQL; Data storage; Records" },
    database_backup: { symbol: "🗂💾", description: "🗂💾 Database backup; Data snapshot" },
    debug_alert: { symbol: "🐞❗", description: "🐞❗ Debug warning; Issue detected" },
    deploy: { symbol: "🚀", description: "🚀 Deployment; Release; Production; Launch" },
    deployment_alert: { symbol: "🚀⚠️", description: "🚀⚠️ Deployment issue; Rollback needed" },
    desktop: { symbol: "🖥", description: "🖥 Desktop; Workstation; Local machine; PC" },
    disk: { symbol: "💽", description: "💽 Disk; Storage; Data persistence; Hard drive" },
    dollar: { symbol: "💲", description: "💲 Cost; Pricing; Currency; Money" },
    encryption: { symbol: "🔒", description: "🔒 Security; Encryption; Protection; Privacy" },
    error: { symbol: "🔥", description: "🔥 Error; Critical issue; Failure; Bug" },
    error_alert: { symbol: "🔥❗", description: "🔥❗ Critical error; System failure; Fire;" },
    error_alert_high: { symbol: "🔥⚠️", description: "🔥⚠️ Critical system failure; Urgent fix needed" },
    feature_flag: { symbol: "✨🚀", description: "✨🚀 Feature flag enabled; New feature release" },
    file: { symbol: "📄", description: "📄 File; Document; Data; Record" },
    file_transfer: { symbol: "📂📤", description: "📂📤 File uploaded; Data transferred" },
    firewall: { symbol: "🛡", description: "🛡 Firewall; Network security; Protection" },
    firewall_block: { symbol: "🛡❌", description: "🛡❌ Firewall block; Connection denied" },
    flashlight: { symbol: "🔦", description: "🔦 Debugging; Inspection; Search; Investigation" },
    folder: { symbol: "📂", description: "📂 Directory; Folder; File storage; Organization" },
    git_branch: { symbol: "🌿", description: "🌿 Git Branch; Version control; Repository" },
    git_merge: { symbol: "🔀", description: "🔀 Git Merge; Combining branches; Integration" },
    git_pull: { symbol: "⬇️", description: "⬇️ Git Pull; Fetch updates; Download" },
    git_push: { symbol: "⬆️", description: "⬆️ Git Push; Send updates; Upload" },
    hacking: { symbol: "🏴‍☠️", description: "🏴‍☠️ Security testing; Ethical hacking; Penetration testing" },
    hammer_wrench: { symbol: "🛠", description: "🛠 Setup; Tools; Configuration; Maintenance" },
    heart: { symbol: "💖", description: "💖 Appreciation; Favorite; Important; Love" },
    high_load: { symbol: "🔥🖥", description: "🔥🖥 High CPU load; Performance issues" },
    hook: { symbol: "🪝", description: "🪝 Hook; Event trigger; Webhook; Callback; Constraint;" },
    hotfix_patch: { symbol: "🔥🔧", description: "🔥🔧 Hotfix patch; Emergency bug fix" },
    http_request: { symbol: "📡", description: "📡 HTTP request; API call; Web request" },
    id_button: { symbol: "🆔", description: "🆔 ID; Identifier; Unique key; Identity" },
    inbox: { symbol: "📥", description: "📥 Incoming request; Data input; Messages" },
    index: { symbol: "📇", description: "📇 Index; Database indexing; Catalog" },
    integration: { symbol: "🔄", description: "🔄 Integration; Middleware; Syncing; Connection" },
    integration_failure: { symbol: "🔄❌", description: "🔄❌ Integration failure; Data sync error" },
    integration_success: { symbol: "🔄✅", description: "🔄✅ Integration successful; Middleware OK" },
    job: { symbol: "💼", description: "💼 Task; Work; Employment; Project" },
    job_queue: { symbol: "💼🔄", description: "💼🔄 Job queue; Processing tasks" },
    key: { symbol: "🔑", description: "🔑 Key; Authentication; Authorization; Access" },
    keyboard: { symbol: "⌨️", description: "⌨️ Keyboard; Typing; Input; Device" },
    kubernetes_deployment: { symbol: "☸️🚀", description: "☸️🚀 Kubernetes deployment; Containerized app" },
    lambda: { symbol: "🔗", description: "🔗 Lambda function; Anonymous function; Serverless" },
    latency: { symbol: "⏳", description: "⏳ Latency; Timeout; Slow response; Delay" },
    lightbulb: { symbol: "💡", description: "💡 Idea; Innovation; Insight; Creativity" },
    lightning: { symbol: "⚡", description: "⚡ Lightning; Fast response; Speed" },
    link: { symbol: "🔗", description: "🔗 Connection; Link; URL; Hyperlink" },
    load_balancing: { symbol: "⚖️📡", description: "⚖️📡 Load balancing; Traffic distribution" },
    log: { symbol: "📜", description: "📜 Log file; System logs; Record" },
    logs_analysis: { symbol: "📜🔍", description: "📜🔍 Log analysis; Debugging process" },
    megaphone: { symbol: "📢", description: "📢 Announcement; Broadcast; Communication" },
    memo: { symbol: "📝", description: "📝 Documentation; Notes; TODO; Memo" },
    merge_conflict: { symbol: "⚔️", description: "⚔️ Merge conflict; Version mismatch; Dispute" },
    metrics: { symbol: "📊", description: "📊 Performance metrics; Monitoring; Statistics" },
    migration_process: { symbol: "📦🔄", description: "📦🔄 Data migration; System transition" },
    mobile: { symbol: "📱", description: "📱 Mobile device; Smartphone; Cellphone" },
    mule: { symbol: "🐴", description: "🐴 MuleSoft; Integration; APIs; Middleware" },
    multiply: { symbol: "✖️", description: "✖️ Multiply; Remove; Close; Cancel" },
    network: { symbol: "📡", description: "📡 Networking; Web requests; Connectivity" },
    network_issue: { symbol: "📡⚠️", description: "📡⚠️ Network issue; Connectivity problem" },
    new: { symbol: "🆕", description: "🆕 New feature; New item; Recent" },
    ok: { symbol: "👌", description: "👌 OK; Success; Good; Approval" },
    ok_button: { symbol: "🆗", description: "🆗 OK; Success; Good; Approval" },
    outbox: { symbol: "📤", description: "📤 Outgoing response; Data output; Sent" },
    package: { symbol: "📦", description: "📦 Package; Software bundle; Shipment" },
    performance: { symbol: "🚀", description: "🚀 Performance optimization; Speed; Efficiency" },
    performance_tuning: { symbol: "🚀⚙️", description: "🚀⚙️ Performance tuning; Optimization process" },
    play_button: { symbol: "▶️", description: "▶️ Play; Start; Run; Execute" },
    plus: { symbol: "➕", description: "➕ Add; Include; Create; Increase" },
    print: { symbol: "🖨️", description: "🖨️ Print; Logging; Debugging; Output" },
    process: { symbol: "⚙️", description: "⚙️ Process execution; Background jobs; Workflow" },
    pushpin: { symbol: "📌", description: "📌 Notes; Pinned item; Important; Reminder" },
    question: { symbol: "❓", description: "❓ Question; Help; Support; Inquiry" },
    queue: { symbol: "🔄", description: "🔄 Task queue; Job scheduling; Line" },
    rainbow: { symbol: "🌈", description: "🌈 Diversity; Creativity; Fun; Inclusion" },
    reboot: { symbol: "🔄", description: "🔄 System reboot; Restart; Refresh" },
    red_circle: { symbol: "⭕", description: "⭕ Error; Critical issue; Alert" },
    refresh: { symbol: "🔄", description: "🔄 Refresh; Retry; Update; Reload" },
    refresh_data: { symbol: "🔄📊", description: "🔄📊 Data refresh; Cache reset" },
    repeat: { symbol: "🔁", description: "🔁 Repeating task; Scheduled jobs; Loop" },
    rollback: { symbol: "⏪", description: "⏪ Rollback; Undo changes; Revert" },
    rollback_action: { symbol: "⏪🛑", description: "⏪🛑 Rollback initiated; Reverting changes" },
    satellite: { symbol: "📡", description: "📡 Satellite system; Remote service; Communication" },
    save: { symbol: "💾", description: "💾 Save; Storage; Backup; Preserve" },
    schedule: { symbol: "⏰", description: "⏰ Scheduled Task; Reminder; Alarm" },
    scheduled_task: { symbol: "⏰🔄", description: "⏰🔄 Scheduled task; CRON job execution" },
    security_key: { symbol: "🔑", description: "🔑 Security key; Authentication; Access" },
    security_warning: { symbol: "🔑⚠️", description: "🔑⚠️ Security risk; Vulnerability detected" },
    server: { symbol: "🖥️", description: "🖥️ Server management; Infrastructure; Hosting" },
    server_down: { symbol: "🖥️❌", description: "🖥️❌ Server down; Outage detected" },
    settings: { symbol: "⚙️", description: "⚙️ Settings; Configuration; Preferences" },
    software: { symbol: "💻", description: "💻 Software; Application; Program" },
    sparkles: { symbol: "✨", description: "✨ Enhancements; New features; Improvements" },
    squirrel: { symbol: "🐿️", description: "🐿️ Squirrel; Caching; Memory; Storage" },
    star: { symbol: "🌟", description: "🌟 Highlight; Important; Favorite" },
    stop_button: { symbol: "⏹️", description: "⏹️ Stop; Terminate; End" },
    stop_sign: { symbol: "🛑", description: "🛑 Stop; Critical issue; Halt" },
    success_logs: { symbol: "✅📜", description: "✅📜 Success logs; No issues found" },
    system_restart: { symbol: "🔄🖥️", description: "🔄🖥️ System reboot; Restart in progress" },
    test_failure: { symbol: "🧪❌", description: "🧪❌ Tests failed; QA issue" },
    test_success: { symbol: "🧪✅", description: "🧪✅ Tests passed; QA successful" },
    test_tube: { symbol: "🧪", description: "🧪 Testing; QA; Validation; Experiment" },
    thumbs_up: { symbol: "👍", description: "👍 Approval; Acceptance; Like; Agree" },
    timeout: { symbol: "⏳", description: "⏳ Timeout; Execution delay; Wait" },
    timeout_error: { symbol: "⏳❌", description: "⏳❌ Timeout; Server delay" },
    todo: { symbol: "📝", description: "📝 To-do tasks; Backlog items; Checklist" },
    transaction: { symbol: "🔄", description: "🔄 Transactions; Process execution; Exchange" },
    transaction_complete: { symbol: "🔄✅", description: "🔄✅ Transaction processed successfully" },
    transaction_failure: { symbol: "🔄❌", description: "🔄❌ Transaction failed; Payment issue" },
    user_authentication: { symbol: "🔑👤", description: "🔑👤 User authentication; Login required" },
    warning: { symbol: "⚠️", description: "⚠️ Warning; Risk; Caution; Alert" },
    warning_logs: { symbol: "⚠️📜", description: "⚠️📜 Warning logs; Investigate further" },
    wastebasket: { symbol: "🗑️", description: "🗑️ Delete; Remove; Trash; Discard" },
    wrench: { symbol: "🔧", description: "🔧 Build; Configuration; Maintenance; Tool" }
};
